DROP TABLE IF EXISTS store_items;
CREATE TABLE store_items (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, price FLOAT(2) NOT NULL, img_name VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS shopping_cart;
CREATE TABLE shopping_cart (id SERIAL PRIMARY KEY, item_id INTEGER NOT NULL, quantity INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (item_id) REFERENCES store_items(id));